# Generated by Django 3.1.7 on 2021-04-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50, unique=True)),
                ('search_date', models.DateField()),
                ('search_time', models.TimeField()),
            ],
        ),
    ]
