# Generated by Django 3.1.7 on 2021-04-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='search_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='search_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
