# Generated by Django 3.1.7 on 2021-04-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20210406_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
